name: Build iOS App

on:
  push:
    branches:
      - main  # O il nome del tuo branch, se diverso

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Step 1: Checkout del codice
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Elenca gli schemi disponibili
      - name: List available schemes
        run: |
          xcodebuild -project ICO-Visualizer.xcodeproj -list

      # Step 3: Installa CocoaPods (se il progetto usa CocoaPods)
      - name: Install dependencies
        run: |
          brew install cocoapods
          pod install

      # Step 4: Esegui la build dell'app
      - name: Build the app
        run: |
          xcodebuild -project ICO-Visualizer.xcodeproj -scheme YourCorrectScheme -verbose
