name: Build iOS App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Pulisce eventuali vecchie dipendenze
      - name: Clean CocoaPods dependencies
        run: |
          rm -rf Pods
          pod deintegrate
          pod install

      # Installa le dipendenze
      - name: Install dependencies
        run: |
          brew install cocoapods
          pod install

      # Esegui la build con Xcode
      - name: Build the app
        run: |
          xcodebuild -workspace YourWorkspace.xcworkspace -scheme YourScheme -verbose
